[package]
name = "xlemma-xlmp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
thiserror.workspace = true
xlemma-core = { path = "../xlemma-core" }

[dev-dependencies]
serde_json.workspace = true
