[package]
name = "xlemma-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
libc.workspace = true
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
xlemma-compute-curve = { path = "../xlemma-compute-curve" }
xlemma-consensus = { path = "../xlemma-consensus" }
xlemma-core = { path = "../xlemma-core" }
xlemma-economics = { path = "../xlemma-economics" }
xlemma-storage = { path = "../xlemma-storage" }
xlemma-xlmp = { path = "../xlemma-xlmp" }
