[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 20000
evm_version = "cancun"

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 128
fail_on_revert = true
